# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Match Cell Barcodes
#'
#' @description Match cell barcodes in the given fastq directory with the reference csv, \code{ref_csv}. Matches are returned
#' in the output file \code{out_fastq}
#'
#' @param fastq_dir directory containing fastq files to match
#' @param stats_file NEEDED
#' @param out_fastq output filename for matched barcodes
#' @param ref_csv NEEDED
#' @param MAX_DIST int; maximum edit distance
#' @param UMI_LEN int; length of UMI sequences
#'
#' @return returns NULL
#' @import zlibbioc
#' @useDynLib FLAMES, .registration=TRUE
match_cell_barcode <- function(fastq_dir, stats_file, out_fastq, ref_csv, MAX_DIST, UMI_LEN = 10L) {
    invisible(.Call(`_FLAMES_match_cell_barcode`, fastq_dir, stats_file, out_fastq, ref_csv, MAX_DIST, UMI_LEN))
}

#' Merge Bulk Fastq Files
#' 
#' @description Merge all fastq files into a single fastq
#' This function also inserts the original fastq file name into the header line of each read.
#'
#' @param fastq_files a string vector of the fastq file paths to merge
#' @param out_fastq the fastq file path of the output file
#' @return returns NULL
#' @useDynLib FLAMES, .registration=TRUE
#' @import zlibbioc
merge_bulk_fastq_cpp <- function(fastq_files, out_fastq) {
    invisible(.Call(`_FLAMES_merge_bulk_fastq_cpp`, fastq_files, out_fastq))
}

