# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' Match Cell Barcodes
#'
#' @description Match cell barcodes in the given fastq directory with the reference csv, \code{ref_csv}. Matches are returned 
#' in the output file \code{out_fastq}
#'
#' @param fast_dir directory containing fastq files to match
#' @param stats_file ?
#' @param out_fastq output filename for matched barcodes
#' @param ref_csv
#' @param MAX_DIST int; maximum edit distance
#' @param UMI_LEN int; length of UMI sequences
#' @useDynLib FlamesR, .registration=TRUE
match_cell_barcode <- function(fastq_dir, stats_file, out_fastq, ref_csv, MAX_DIST, UMI_LEN = 10L) {
    .Call('_FlamesR_match_cell_barcode', PACKAGE = 'FlamesR', fastq_dir, stats_file, out_fastq, ref_csv, MAX_DIST, UMI_LEN)
}

